package org.prathyushacampus.codeathonteamdashboardbackend.model;

public enum Theme {
    NATIONAL_SECURITY,
    HEALTHCARE,
    EMERGENCY_MANAGEMENT,
    ENVIRONMENT_AND_SUSTAINABILITY,
    SMART_CITY,
    SMART_HOME,
    SMART_EDUCATION,
    SECURE_DIGITAL_TRANSACTIONS_AND_LOGISTICS,
    RURAL_DEVELOPMENT,
    ZERO_HUNGER,
    GOOD_HEALTH_AND_WELL_BEING,
    QUALITY_EDUCATION,
    CLEAN_WATER_AND_SANITATION,
    AFFORDABLE_AND_CLEAN_ENERGY,
    AQUATIC_LIFE,
    CLIMATE_ACTION,
    LIFE_ON_LAND,
}
